# Generated by Django 4.2.5 on 2023-10-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_result_hotel_alter_hotel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
