# Generated by Django 4.2.5 on 2023-10-11 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_hotel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
    ]
