# Generated by Django 4.2.5 on 2023-10-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'managed': False},
        ),
    ]
