# Generated by Django 4.2.5 on 2023-10-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_record_zipcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
