# Generated by Django 4.2.5 on 2023-11-04 11:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0015_hotelbooking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelBooking',
            new_name='Booking',
        ),
    ]
