# Generated by Django 4.2.5 on 2023-11-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_rename_hotelbooking_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
