# Generated by Django 4.2.5 on 2023-11-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_bookingofhotel_hotel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingofhotel',
            name='hotel_name',
        ),
    ]
