# Generated by Django 4.2.5 on 2023-11-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_checkin_delete_bookingofhotel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checkin',
            new_name='CheckInOut',
        ),
    ]
