# Generated by Django 4.2.5 on 2023-11-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_rename_checkin_checkinout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckInOut',
        ),
    ]
