# Generated by Django 4.2.5 on 2023-11-04 14:13

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_delete_checkinout'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orders',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name=django.contrib.auth.models.User),
            preserve_default=False,
        ),
    ]
